**Notebook content:**
- Add columns such as "featurName" and "category", using file "eventsInfo"
- Convert units to keep uniformity.

In [37]:
%reset -f

In [38]:
from myDefs.defs import *
from IPython.display import display

pd.set_option('display.max_columns', 30)
pd.set_option('display.max_rows', 200)
#pd.set_option('display.float_format', lambda x: '%.f' % x)
pd.options.display.precision = 4

#import sys
np.set_printoptions(threshold=sys.maxsize) #- print the full NumPy array

In [39]:
OUTPUT_PATH = DATA_PATH + "parseData2.csv"

### **Read files**

In [40]:
#read events file 
path = DATA_PATH + "parseData1.csv"
df = pd.read_csv(path, sep=',')

In [41]:
#read events info
eventsinfo = pd.read_excel(ORGANIZE_EVENTS_PATH + "EventsInfo.xlsx")

In [42]:
print(df.shape)
print(eventsinfo.shape)

(1683616, 18)
(3755, 18)

In [81]:
eventsinfo[['eventName', 'featureName', 'inModel', 'category', 'count', 'nPatients', 'dValues', 'source']].sort_values(by='inModel', ascending=False).head()

,eventName,featureName,inModel,category,count,nPatients,dValues,source
5,%Reticulo,Reticulocytes (%),1.0,laboratory,239,89,"{'count': 239.0, 'mean': 2.6644351464435165, '...",['Lab Results']
1693,NORADRENALINE/ NOREPINEPHRINE BITARTRATE 4 mg ...,Norepinephrine + dextrose,1.0,drug,15,1,4,['Med Execution Medicine']
1685,NORADRENALINE/ NOREPINEPHRINE BITARTRATE 4 mg ...,Norepinephrine + dextrose,1.0,drug,3,1,4,['Med Execution Medicine']
1686,NORADRENALINE/ NOREPINEPHRINE BITARTRATE 4 mg ...,Norepinephrine + dextrose,1.0,drug,4,2,4,['Med Execution Medicine']
1687,NORADRENALINE/ NOREPINEPHRINE BITARTRATE 4 mg ...,Norepinephrine + dextrose,1.0,drug,12,5,4,['Med Execution Medicine']

# Add new columns

## "featureName"

In [43]:
#create new column feature name 
names_dict = dict(zip(eventsinfo['eventName'], eventsinfo['featureName']))
df['featureName'] = df['eventName'].map(names_dict, na_action='ignore')

In [44]:
df['featureName'].nunique()

2488

In [45]:
df.head()

,pid,admissionId,eventName,eventStartDate,eventEndDate,dValue,iValue,sValue,eventDesc,unitOfMeasure,orderNumber,organismId,eventCode,eventCodeOrg,eventType,eventTypeOrg,sourceName,source,featureName
0,1.0133e+09,1840641.0,WBC,2018-02-15 10:58:00.0000000,2018-02-15 10:58:00.0000000,2.14,0.0,NaN,NaN,K/microL,NaN,NaN,26464-8,100109500,loinc,conv_lab_cham,[MIRROR_Chameleon].[Lab_Results],Lab Results,WBC
1,1.0133e+09,1840641.0,Alkaline Phosphatase -Blood,2018-02-15 10:25:00.0000000,2018-02-15 10:25:00.0000000,129.00,0.0,NaN,NaN,IU/l,NaN,NaN,77141-0,100184075,loinc,conv_lab_cham,[MIRROR_Chameleon].[Lab_Results],Lab Results,Alkaline Phosphatase
2,1.0133e+09,1840641.0,"Protein -Blood, total",2018-02-15 10:25:00.0000000,2018-02-15 10:25:00.0000000,3.60,0.0,NaN,NaN,g/dl,NaN,NaN,2885-2,100184155,loinc,conv_lab_cham,[MIRROR_Chameleon].[Lab_Results],Lab Results,"Protein, total"
3,1.0133e+09,1840641.0,Sodium -Blood,2018-02-15 10:25:00.0000000,2018-02-15 10:25:00.0000000,147.00,0.0,NaN,NaN,meq/l,NaN,NaN,2951-2,100184295,loinc,conv_lab_cham,[MIRROR_Chameleon].[Lab_Results],Lab Results,Sodium
4,1.0133e+09,1840641.0,Urea -Blood,2018-02-15 10:25:00.0000000,2018-02-15 10:25:00.0000000,24.00,0.0,NaN,NaN,mg/dl,NaN,NaN,3091-6,100184520,loinc,conv_lab_cham,[MIRROR_Chameleon].[Lab_Results],Lab Results,Urea

## "numeric", replace values (sValue -> dValue)

In [46]:
def convert_to_dict(x):
    d = json.loads(x)
    for key in d:
        if d[key] == 'None':
            d[key] = None
    return d

'''
 try:
        d = json.loads(x)
    except:
        display(x)
        return
'''

#convert dict column to dictionary 
eventsinfo.loc[eventsinfo['dict'].notna(),'dict'] = eventsinfo.loc[eventsinfo['dict'].notna(),'dict'].apply(convert_to_dict)

In [47]:
#replace dValue by values in dictionary
def replace_values(x, info):
    #get dictionary 
    d = info.loc[info['eventName'] == x['eventName'].iloc[0], 'dict'].iloc[0]
    #copy sValue to dValue
    x.loc[x['sValue'].notna(),'dValue'] = x['sValue']
    #replace dValues by by sValues 
    return x['dValue'].replace(d)

#replace values
df['numeric'] = df.groupby('eventName', group_keys=False).apply(replace_values, eventsinfo)

In [48]:
#convert column to numeric
df['numeric'] = pd.to_numeric(df['numeric'], downcast='float', errors='coerce')

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1683616 entries, 0 to 1683615
Data columns (total 20 columns):
pid               1683616 non-null float64
admissionId       1683616 non-null float64
eventName         1628158 non-null object
eventStartDate    1683616 non-null object
eventEndDate      1683616 non-null object
dValue            1556931 non-null float64
iValue            1556931 non-null float64
sValue            38589 non-null object
eventDesc         136875 non-null object
unitOfMeasure     966464 non-null object
orderNumber       16699 non-null float64
organismId        2126 non-null float64
eventCode         1683616 non-null object
eventCodeOrg      1534034 non-null object
eventType         1683616 non-null object
eventTypeOrg      1541809 non-null object
sourceName        1683577 non-null object
source            1683577 non-null object
featureName       1628158 non-null object
numeric           1585705 non-null float32
dtypes: float32(1), float64(6), object(13)
memory usage: 250.5+ MB

## "unit"

In [50]:
#create new column of unit
df['unit'] = df['unitOfMeasure']

## "category"

In [51]:
#category 
category_dict = dict(zip(eventsinfo['eventName'], eventsinfo['category']))
df['category'] = df['eventName'].map(category_dict)

## "inModel"

In [52]:
#if feature is in Model  
inmodel_dict = dict(zip(eventsinfo['eventName'], eventsinfo['inModel']))
df['inModel'] = df['eventName'].map(inmodel_dict)

## Reorder columns

In [53]:
df = df[['pid', 'eventName', 
         'featureName','eventStartDate', 'eventEndDate',  'numeric', 'unit', 'category', 'inModel',
         'dValue', 'iValue', 'sValue', 'eventDesc', 'unitOfMeasure', 'source', 'sourceName',
         'orderNumber', 'organismId', 'eventCode', 'eventCodeOrg', 'eventType', 'eventTypeOrg']]

In [54]:
df.columns

Index(['pid', 'eventName', 'featureName', 'eventStartDate', 'eventEndDate',
       'numeric', 'unit', 'category', 'inModel', 'dValue', 'iValue', 'sValue',
       'eventDesc', 'unitOfMeasure', 'source', 'sourceName', 'orderNumber',
       'organismId', 'eventCode', 'eventCodeOrg', 'eventType', 'eventTypeOrg'],
      dtype='object')

In [55]:
df.head()

,pid,eventName,featureName,eventStartDate,eventEndDate,numeric,unit,category,inModel,dValue,iValue,sValue,eventDesc,unitOfMeasure,source,sourceName,orderNumber,organismId,eventCode,eventCodeOrg,eventType,eventTypeOrg
0,1.0133e+09,WBC,WBC,2018-02-15 10:58:00.0000000,2018-02-15 10:58:00.0000000,2.14,K/microL,laboratory,1.0,2.14,0.0,NaN,NaN,K/microL,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,26464-8,100109500,loinc,conv_lab_cham
1,1.0133e+09,Alkaline Phosphatase -Blood,Alkaline Phosphatase,2018-02-15 10:25:00.0000000,2018-02-15 10:25:00.0000000,129.00,IU/l,laboratory,1.0,129.00,0.0,NaN,NaN,IU/l,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,77141-0,100184075,loinc,conv_lab_cham
2,1.0133e+09,"Protein -Blood, total","Protein, total",2018-02-15 10:25:00.0000000,2018-02-15 10:25:00.0000000,3.60,g/dl,laboratory,1.0,3.60,0.0,NaN,NaN,g/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,2885-2,100184155,loinc,conv_lab_cham
3,1.0133e+09,Sodium -Blood,Sodium,2018-02-15 10:25:00.0000000,2018-02-15 10:25:00.0000000,147.00,meq/l,laboratory,1.0,147.00,0.0,NaN,NaN,meq/l,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,2951-2,100184295,loinc,conv_lab_cham
4,1.0133e+09,Urea -Blood,Urea,2018-02-15 10:25:00.0000000,2018-02-15 10:25:00.0000000,24.00,mg/dl,laboratory,1.0,24.00,0.0,NaN,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3091-6,100184520,loinc,conv_lab_cham

# Convert units

In [56]:
#see which events should be converted
eventsinfo.loc[eventsinfo['inModel'] == 1].loc[eventsinfo['category']!='drug'] \
.loc[eventsinfo['multiUnits'].notna(), ['eventName', 'featureName', 'unit']]

,eventName,featureName,unit
2081,Potassium,Potassium,"['mmol/L', 'mmol/l', 'meq/l']"
2391,Sodium,Sodium,"['mmol/L', 'mmol/l', 'meq/l']"
2635,Temperature,body temperature,['F']
2825,WBC,WBC,"['cells/mm3', 'K/microL', 'LEU/UL', '/HPF']"
3156,חום,body temperature,"['C', 'F']"

#### Body temperature

In [57]:
def fahrenheit_to_celsius(f):
    return (f - 32) * 5.0/9.0

temp_ix = df.loc[df['featureName'] == 'body temperature'].loc[df['unitOfMeasure'] == 'F'].index
df.loc[temp_ix, 'numeric'] = df.loc[temp_ix, 'numeric'].apply(fahrenheit_to_celsius)
df.loc[temp_ix, 'unit'] = 'C'

#remove noise
temp = df.loc[df['featureName'] == 'body temperature', 'numeric']
temp_ix = temp[temp > 45].index
df.loc[temp_ix, 'numeric'] = None

#### WBC

In [58]:
df.loc[df['eventName'] == 'WBC'].head()

,pid,eventName,featureName,eventStartDate,eventEndDate,numeric,unit,category,inModel,dValue,iValue,sValue,eventDesc,unitOfMeasure,source,sourceName,orderNumber,organismId,eventCode,eventCodeOrg,eventType,eventTypeOrg
0,1.0133e+09,WBC,WBC,2018-02-15 10:58:00.0000000,2018-02-15 10:58:00.0000000,2.14,K/microL,laboratory,1.0,2.14,0.0,NaN,NaN,K/microL,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,26464-8,100109500,loinc,conv_lab_cham
29,1.0133e+09,WBC,WBC,2018-02-15 10:58:00.0000000,2018-02-15 10:58:00.0000000,2.14,K/microL,laboratory,1.0,2.14,0.0,NaN,NaN,K/microL,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,26464-8,100109500,loinc,conv_lab_cham
193,7.4266e+07,WBC,WBC,2018-02-18 12:22:00.0000000,2018-02-18 12:22:00.0000000,11.12,K/microL,laboratory,1.0,11.12,0.0,NaN,NaN,K/microL,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,26464-8,100109500,loinc,conv_lab_cham
758,1.0133e+09,WBC,WBC,2018-02-10 16:22:00.0000000,2018-02-10 16:22:00.0000000,7.65,K/microL,laboratory,1.0,7.65,0.0,NaN,NaN,K/microL,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,26464-8,100109500,loinc,conv_lab_cham
867,4.8546e+08,WBC,WBC,2018-02-16 09:28:00.0000000,2018-02-16 09:28:00.0000000,8.42,K/microL,laboratory,1.0,8.42,0.0,NaN,NaN,K/microL,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,26464-8,100109500,loinc,conv_lab_cham

In [59]:
wbc = df.loc[df['eventName'] == 'WBC', 'unitOfMeasure'].value_counts()
display(wbc)

i = 1
for unit in wbc.head(3).index:
    wbc_ix = df.loc[df['featureName'] == 'WBC'].loc[df['unitOfMeasure'] == unit].index
    df.loc[wbc_ix, 'featureName'] = 'WBC_' + str(i)
    df.loc[wbc_ix, 'unit'] = unit
    i += 1

K/microL     14626
/HPF           468
LEU/UL         137
cells/mm3        5
Name: unitOfMeasure, dtype: int64

#### Weight

In [60]:
#convert to kg 
weight_ix = df.loc[df['eventName'] == 'CurrentWeight'].index
df.loc[weight_ix, 'numeric'] = df.loc[weight_ix, 'numeric'].apply(lambda x: x/1000)
df.loc[weight_ix, 'unit'] = 'kg'

#### Hight

In [61]:
hight_ix = df.loc[df['eventName'] == 'height'].index

In [62]:
#convert to cm
df.loc[459519, 'numeric'] = df.loc[459519, 'numeric'] * 100

#### Potassium and Sodium
mmol/l == meq/l
so don't need to convert

In [65]:
df.loc[(df['eventName'] == 'Uric acid -Blood') & df['sValue'].notna()]

,pid,eventName,featureName,eventStartDate,eventEndDate,numeric,unit,category,inModel,dValue,iValue,sValue,eventDesc,unitOfMeasure,source,sourceName,orderNumber,organismId,eventCode,eventCodeOrg,eventType,eventTypeOrg
28952,1.0133e+09,Uric acid -Blood,Uric acid,2018-03-20 11:09:00.0000000,2018-03-20 11:09:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
72794,6.3271e+08,Uric acid -Blood,Uric acid,2018-07-04 05:36:00.0000000,2018-07-04 05:36:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
82115,6.4436e+08,Uric acid -Blood,Uric acid,2018-07-26 04:38:00.0000000,2018-07-26 04:38:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
82361,6.4436e+08,Uric acid -Blood,Uric acid,2018-07-28 05:10:00.0000000,2018-07-28 05:10:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
94875,6.4436e+08,Uric acid -Blood,Uric acid,2018-07-27 04:56:00.0000000,2018-07-27 04:56:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
139460,6.3271e+08,Uric acid -Blood,Uric acid,2018-07-05 05:28:00.0000000,2018-07-05 05:28:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
186446,1.1339e+07,Uric acid -Blood,Uric acid,2018-10-28 03:48:00.0000000,2018-10-28 03:48:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
206141,1.1339e+07,Uric acid -Blood,Uric acid,2018-10-29 03:57:00.0000000,2018-10-29 03:57:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
215981,6.3271e+08,Uric acid -Blood,Uric acid,2018-07-06 12:58:00.0000000,2018-07-06 12:58:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
259665,7.7843e+08,Uric acid -Blood,Uric acid,2019-04-18 13:23:00.0000000,2019-04-18 13:23:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
281442,5.3598e+08,Uric acid -Blood,Uric acid,2018-04-14 05:20:00.0000000,2018-04-14 05:20:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
285016,5.3598e+08,Uric acid -Blood,Uric acid,2018-04-15 04:55:00.0000000,2018-04-15 04:55:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
287895,1.1157e+08,Uric acid -Blood,Uric acid,2018-06-07 19:19:00.0000000,2018-06-07 19:19:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
294242,7.7843e+08,Uric acid -Blood,Uric acid,2019-04-19 09:19:00.0000000,2019-04-19 09:19:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
300067,7.7843e+08,Uric acid -Blood,Uric acid,2019-04-17 06:14:00.0000000,2019-04-17 06:14:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
334927,9.8230e+08,Uric acid -Blood,Uric acid,2019-01-21 13:30:00.0000000,2019-01-21 13:30:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
355200,9.8230e+08,Uric acid -Blood,Uric acid,2019-04-28 01:02:00.0000000,2019-04-28 01:02:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
363240,9.8230e+08,Uric acid -Blood,Uric acid,2019-05-06 11:22:00.0000000,2019-05-06 11:22:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
392631,6.2844e+08,Uric acid -Blood,Uric acid,2017-11-28 11:26:00.0000000,2017-11-28 11:26:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,מתחת לגבול דינמי תחתון1.2,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
393007,6.2844e+08,Uric acid -Blood,Uric acid,2017-12-01 08:55:00.0000000,2017-12-01 08:55:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,מתחת לגבול דינמי תחתון1.2,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
393070,6.3738e+08,Uric acid -Blood,Uric acid,2017-12-14 08:05:00.0000000,2017-12-14 08:05:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,מתחת לגבול דינמי תחתון1.4,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
429144,7.9987e+08,Uric acid -Blood,Uric acid,2018-05-29 23:21:00.0000000,2018-05-29 23:21:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
563696,9.8080e+08,Uric acid -Blood,Uric acid,2018-11-25 21:16:00.0000000,2018-11-25 21:16:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
576212,4.4980e+08,Uric acid -Blood,Uric acid,2018-12-31 13:54:00.0000000,2018-12-31 13:54:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
583251,4.4980e+08,Uric acid -Blood,Uric acid,2019-02-11 10:14:00.0000000,2019-02-11 10:14:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
603545,1.0795e+08,Uric acid -Blood,Uric acid,2018-05-07 14:02:00.0000000,2018-05-07 14:02:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
604326,1.0795e+08,Uric acid -Blood,Uric acid,2018-05-15 21:54:00.0000000,2018-05-15 21:54:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
605937,1.0795e+08,Uric acid -Blood,Uric acid,2018-05-28 15:05:00.0000000,2018-05-28 15:05:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
605987,1.0795e+08,Uric acid -Blood,Uric acid,2018-05-29 17:21:00.0000000,2018-05-29 17:21:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
606053,1.0795e+08,Uric acid -Blood,Uric acid,2018-05-30 22:02:00.0000000,2018-05-30 22:02:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
606103,1.0795e+08,Uric acid -Blood,Uric acid,2018-05-31 14:15:00.0000000,2018-05-31 14:15:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
606128,1.0795e+08,Uric acid -Blood,Uric acid,2018-06-01 11:00:00.0000000,2018-06-01 11:00:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
606307,1.0795e+08,Uric acid -Blood,Uric acid,2018-06-02 12:49:00.0000000,2018-06-02 12:49:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
606347,1.0795e+08,Uric acid -Blood,Uric acid,2018-06-03 14:53:00.0000000,2018-06-03 14:53:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
606380,1.0795e+08,Uric acid -Blood,Uric acid,2018-06-04 10:52:00.0000000,2018-06-04 10:52:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
606432,1.0795e+08,Uric acid -Blood,Uric acid,2018-06-05 15:57:00.0000000,2018-06-05 15:57:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
606482,1.0795e+08,Uric acid -Blood,Uric acid,2018-06-06 13:09:00.0000000,2018-06-06 13:09:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
607033,1.0795e+08,Uric acid -Blood,Uric acid,2018-06-13 12:08:00.0000000,2018-06-13 12:08:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
609269,1.0795e+08,Uric acid -Blood,Uric acid,2018-07-07 10:47:00.0000000,2018-07-07 10:47:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
632831,5.9233e+08,Uric acid -Blood,Uric acid,2017-12-28 20:32:00.0000000,2017-12-28 20:32:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,מתחת לגבול דינמי תחתון1.1,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
635888,7.6137e+08,Uric acid -Blood,Uric acid,2018-01-24 12:24:00.0000000,2018-01-24 12:24:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,מתחת לגבול דינמי תחתון1.1,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
641632,6.6689e+08,Uric acid -Blood,Uric acid,2018-05-17 07:24:00.0000000,2018-05-17 07:24:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
642384,5.9233e+08,Uric acid -Blood,Uric acid,2018-02-02 00:18:00.0000000,2018-02-02 00:18:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,מתחת לגבול דינמי תחתון1.2,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
647284,6.6689e+08,Uric acid -Blood,Uric acid,2018-05-21 06:01:00.0000000,2018-05-21 06:01:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
660426,5.9233e+08,Uric acid -Blood,Uric acid,2018-01-09 11:00:00.0000000,2018-01-09 11:00:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,מתחת לגבול דינמי תחתון1.0,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
661083,5.9233e+08,Uric acid -Blood,Uric acid,2018-01-30 10:36:00.0000000,2018-01-30 10:36:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,מתחת לגבול דינמי תחתון1.3,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
661238,5.9233e+08,Uric acid -Blood,Uric acid,2018-01-31 15:07:00.0000000,2018-01-31 15:07:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,מתחת לגבול דינמי תחתון1.3,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
662083,6.6689e+08,Uric acid -Blood,Uric acid,2018-05-05 06:24:00.0000000,2018-05-05 06:24:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
662148,6.6689e+08,Uric acid -Blood,Uric acid,2018-05-06 07:09:00.0000000,2018-05-06 07:09:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
662242,6.6689e+08,Uric acid -Blood,Uric acid,2018-05-07 06:00:00.0000000,2018-05-07 06:00:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
662314,6.6689e+08,Uric acid -Blood,Uric acid,2018-05-08 08:51:00.0000000,2018-05-08 08:51:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
662400,6.6689e+08,Uric acid -Blood,Uric acid,2018-05-10 09:17:00.0000000,2018-05-10 09:17:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
663758,5.9233e+08,Uric acid -Blood,Uric acid,2018-01-14 13:20:00.0000000,2018-01-14 13:20:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,מתחת לגבול דינמי תחתון1.3,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
676776,6.6978e+08,Uric acid -Blood,Uric acid,2018-04-22 05:56:00.0000000,2018-04-22 05:56:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
681603,6.6689e+08,Uric acid -Blood,Uric acid,2018-05-23 10:06:00.0000000,2018-05-23 10:06:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
688992,6.6689e+08,Uric acid -Blood,Uric acid,2018-04-17 06:55:00.0000000,2018-04-17 06:55:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
694945,6.6689e+08,Uric acid -Blood,Uric acid,2018-04-18 07:02:00.0000000,2018-04-18 07:02:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
703392,6.6689e+08,Uric acid -Blood,Uric acid,2018-04-19 04:42:00.0000000,2018-04-19 04:42:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
780373,1.0505e+07,Uric acid -Blood,Uric acid,2019-05-07 09:42:00.0000000,2019-05-07 09:42:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
791739,1.0505e+07,Uric acid -Blood,Uric acid,2019-05-09 22:23:00.0000000,2019-05-09 22:23:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
792117,1.0505e+07,Uric acid -Blood,Uric acid,2019-05-06 13:16:00.0000000,2019-05-06 13:16:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
798073,1.0505e+07,Uric acid -Blood,Uric acid,2019-05-12 09:42:00.0000000,2019-05-12 09:42:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
810978,1.0505e+07,Uric acid -Blood,Uric acid,2019-05-16 11:38:00.0000000,2019-05-16 11:38:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
811582,1.0738e+07,Uric acid -Blood,Uric acid,2018-10-19 08:26:00.0000000,2018-10-19 08:26:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
844813,6.7372e+08,Uric acid -Blood,Uric acid,2018-06-03 06:14:00.0000000,2018-06-03 06:14:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
845376,6.7372e+08,Uric acid -Blood,Uric acid,2018-06-04 05:47:00.0000000,2018-06-04 05:47:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
852939,6.7372e+08,Uric acid -Blood,Uric acid,2018-05-28 05:36:00.0000000,2018-05-28 05:36:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
857339,6.7372e+08,Uric acid -Blood,Uric acid,2018-05-29 05:14:00.0000000,2018-05-29 05:14:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
866087,6.7372e+08,Uric acid -Blood,Uric acid,2018-05-30 06:01:00.0000000,2018-05-30 06:01:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
866188,6.7372e+08,Uric acid -Blood,Uric acid,2018-05-31 06:32:00.0000000,2018-05-31 06:32:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
867929,6.7372e+08,Uric acid -Blood,Uric acid,2018-05-14 22:04:00.0000000,2018-05-14 22:04:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
868126,6.7372e+08,Uric acid -Blood,Uric acid,2018-05-15 04:14:00.0000000,2018-05-15 04:14:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
869820,6.7372e+08,Uric acid -Blood,Uric acid,2018-06-01 04:26:00.0000000,2018-06-01 04:26:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
884578,7.7797e+08,Uric acid -Blood,Uric acid,2018-07-09 07:11:00.0000000,2018-07-09 07:11:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
891324,7.7797e+08,Uric acid -Blood,Uric acid,2018-07-10 05:50:00.0000000,2018-07-10 05:50:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
891378,7.7797e+08,Uric acid -Blood,Uric acid,2018-07-10 10:08:00.0000000,2018-07-10 10:08:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
891562,7.7797e+08,Uric acid -Blood,Uric acid,2018-07-11 06:49:00.0000000,2018-07-11 06:49:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,<1.5,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
898430,7.4584e+08,Uric acid -Blood,Uric acid,2017-09-27 19:26:00.0000000,2017-09-27 19:26:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,מתחת לגבול דינמי תחתון0.9,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
899031,7.4584e+08,Uric acid -Blood,Uric acid,2017-09-28 04:46:00.0000000,2017-09-28 04:46:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,מתחת לגבול דינמי תחתון1.0,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
902228,7.4584e+08,Uric acid -Blood,Uric acid,2017-09-29 06:07:00.0000000,2017-09-29 06:07:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,מתחת לגבול דינמי תחתון0.6,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham
903841,7.4584e+08,Uric acid -Blood,Uric acid,2017-09-30 05:48:00.0000000,2017-09-30 05:48:00.0000000,NaN,mg/dl,laboratory,NaN,0.0,0.0,מתחת לגבול דינמי תחתון0.7,NaN,mg/dl,Lab Results,[MIRROR_Chameleon].[Lab_Results],NaN,NaN,3084-1,100184550,loinc,conv_lab_cham

# Write outputs

In [224]:
#output into one file 
if WRITE_FLAG:
    df.to_csv(OUTPUT_PATH, sep=',', index=False)

### drugs

In [226]:
#write list of drugs
drugs = df[df['category']=='drug'].groupby(['featureName'])['pid'].nunique().sort_values(ascending=False).to_frame().reset_index()
if WRITE_FLAG:
    drugs.to_excel(ORGANIZE_EVENTS_PATH + "drugs.xlsx", index=False)